# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colMSD_dgc <- function(mat, m) {
    .Call(`_rpc_colMSD_dgc`, mat, m)
}

colMSD_matrix <- function(X, meanX) {
    .Call(`_rpc_colMSD_matrix`, X, meanX)
}

#'Compute the ridge partial correlation
NULL

compute_rpc <- function(Z, colMeansZ, rowSumS, y, D, theta, ncores = 4L) {
    .Call(`_rpc_compute_rpc`, Z, colMeansZ, rowSumS, y, D, theta, ncores)
}

#' Compute the cross product of a sparse matrix X
NULL

.getXXt_dense <- function(mat, mX, Dvec, ncores = 4L, chunksize = 1000L) {
    .Call(`_rpc___getXXt_dense__`, mat, mX, Dvec, ncores, chunksize)
}

#' Compute the cross product of a sparse matrix X
NULL

.getXXt_sparse <- function(mat, D, ncores = 4L, chunksize = 1000L) {
    .Call(`_rpc___getXXt_sparse__`, mat, D, ncores, chunksize)
}

